#mongodb note:mongo3.x will not use host and port,only use uri
spring.data.mongodb.host=192.168.163.36
spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb://192.168.163.36:27017/wisdombudfile